name: "build"
on:
  push:
  pull_request:
  schedule:
    - cron: "* * */15 * *"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v1"
        with:
          go-version: "1.13"
      - run: "./build.bash"
      - run: "git diff --cached --exit-code"
